# This file is automatically generated. Do not edit.

PXEngine.licenseKey('FI33P-U01A0-LRQL4-7VOL4-OO1MA-JI1B9-SDF9Q-TCSFU-5OCOJ-C5CH1-I7FEI-SGRAU-07LS6-54M43-V7JGP-PM', forUser:'s.namai.09@gmail.com')

def style(str)
  PXEngine.styleSheetFromSource(str, withOrigin:0)
  PXEngine.applyStylesheets
end
